version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 jenkins:
  # build: ./jenkins
  image: derekbasch/docker-jenkins-pipeline
  ports:
    - "8080:8080"
  networks:
    - prodnetwork
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker
  depends_on:
    - selhub

 selhub:
  image: selenium/hub
  ports:
    - 4444:4444
  networks:
    - prodnetwork

 nodeff:
  image: selenium/node-firefox-debug
  ports:
    - 5900
  networks:
    - prodnetwork
  environment:
   - HUB_PORT_4444_TCP_ADDR=selhub
  depends_on:
    - selhub